version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: products_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: products
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: products_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: